### PR TITLE
Adding contribution guidelines

### PR DESCRIPTION
**Pull request by Lun4m**
This is a simple draft. It needs to be improved further. 

- [x] Add [co-authorship](https://github.blog/2018-01-29-commit-together-with-co-authors/)

### CODE REVIEW

**Comment by mortele** [comment]
Lets discuss finishing up these guidelines in the office tomorrow, @samiransen23 @Lun4m 👍🏻

**Comment by samiransen23** [comment]
@mortele, @Lun4m  : Yes, we have a few community guidelines written. There isn't much to discuss, but we'll run it by you.

**Comment by hmcezar** [comment]
The guidelines seem fine to me. Maybe we could add some more instructions for the PRs, like having a clear list of the fixes/features of that PR.

**Comment by Lun4m** [comment]
I think I'm done, just leave a thumbs up on this comment if you feel like it's good enough and I will merge it later today.

**Review by mortele — APPROVED** [review]

**Pull request merged**
